export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILUSERS';

export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILUSERS';

export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const FETCH_CUSTOMERS_COMPANIES_START = 'FETCH_CUSTOMERS_COMPANIES_START';
export const FETCH_CUSTOMERS_COMPANIES_SUCCESS = 'FETCH_CUSTOMERS_COMPANIES_SUCCESS';
export const FETCH_CUSTOMERS_COMPANIES_FAILURE = 'FETCH_CUSTOMERS_COMPANIES_FAILURE';

export const FETCH_CUSTOMERS_PRIVATE_START = 'FETCH_CUSTOMERS_PRIVATE_START';
export const FETCH_CUSTOMERS_PRIVATE_SUCCESS = 'FETCH_CUSTOMERS_PRIVATE_SUCCESS';
export const FETCH_CUSTOMERS_PRIVATE_FAILURE = 'FETCH_CUSTOMERS_PRIVATE_FAILURE';

export const FETCH_CUSTOMERS_START = 'FETCH_CUSTOMERS_START'; 
export const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS'; 
export const FETCH_CUSTOMERS_FAILURE = 'FETCH_CUSTOMERS_FAILURE';

export const UPDATE_CUSTOMER_START = 'UPDATE_CUSTOMER_START';
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS';
export const UPDATE_CUSTOMER_FAILURE = 'UPDATE_CUSTOMER_FAILURE';

export const FETCH_EMPLOYEES_START = 'FETCH_EMPLOYEES_START';
export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS';
export const FETCH_EMPLOYEES_FAILURE = 'FETCH_EMPLOYEES_FAILURE';

export const CREATE_USER_START = 'CREATE_USER_START';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';  
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

export const DELETE_USER_START = 'DELETE_USER_START';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';  
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';
