export const FETCH_SERVICES_START = 'FETCH_SERVICES_START';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';
export const FETCH_SERVICES_FAILURE = 'FETCH_SERVICES_FAILURE';

export const ORDER_CREATE_START = 'ORDER_CREATE_START';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAILURE = 'ORDER_CREATE_FAILURE';

export const COMPLAINT_CREATE_START = 'COMPLAINT_CREATE_START';
export const COMPLAINT_CREATE_SUCCESS = 'COMPLAINT_CREATE_SUCCESS';
export const COMPLAINT_CREATE_FAILURE = 'COMPLAINT_CREATE_FAILURE';

export const FETCH_EMPLOYEES_START = 'FETCH_EMPLOYEES_START';
export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS';
export const FETCH_EMPLOYEES_FAILURE = 'FETCH_EMPLOYEES_FAILURE';

export const FETCH_DONE_START = 'FETCH_DONE_START';
export const FETCH_DONE_SUCCESS = 'FETCH_DONE_SUCCESS';
export const FETCH_DONE_FAILURE = 'FETCH_DONE_FAILURE';

export const SEND_CUSTOMER_NOTIFICATION = 'SEND_CUSTOMER_NOTIFICATION';
