// Incoming for employee
export const FETCH_EMP_ASSIGNED_REQUEST = 'FETCH_EMP_ASSIGNED_REQUEST';
export const FETCH_EMP_ASSIGNED_SUCCESS = 'FETCH_EMP_ASSIGNED_SUCCESS';
export const FETCH_EMP_ASSIGNED_FAILURE = 'FETCH_EMP_ASSIGNED_FAILURE';

// Done for employee
export const FETCH_EMP_DONE_REQUEST = 'FETCH_EMP_DONE_REQUEST';
export const FETCH_EMP_DONE_SUCCESS = 'FETCH_EMP_DONE_SUCCESS';
export const FETCH_EMP_DONE_FAILURE = 'FETCH_EMP_DONE_FAILURE';

export const FETCH_SERVICE_COMPLETE_START = 'FETCH_SERVICE_COMPLETE_START';
export const FETCH_SERVICE_COMPLETE_SUCCESS = 'FETCH_SERVICE_COMPLETE_SUCCESS';
export const FETCH_SERVICE_COMPLETE_FAILURE = 'FETCH_SERVICE_COMPLETE_FAILURE';

export const SEND_EMPLOYEE_NOTIFICATION = 'SEND_EMPLOYEE_NOTIFICATION';

export const SAVE_PHOTOS_SUCCESS = 'SAVE_PHOTOS_SUCCESS';
export const SAVE_PHOTOS_FAILURE = 'SAVE_PHOTOS_FAILURE';
