export const FETCH_SERVICE_START = 'FETCH_SERVICE_START';
export const FETCH_SERVICE_SUCCESS = 'FETCH_SERVICE_SUCCESS';
export const FETCH_SERVICE_FAILURE = 'FETCH_SERVICE_FAILURE';

export const FETCH_SERVICES_START = 'FETCH_SERVICES_START';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';
export const FETCH_SERVICES_FAILURE = 'FETCH_SERVICES_FAILURE';

export const FETCH_NEW_SERVICES_START = 'FETCH_NEW_SERVICES_START';
export const FETCH_NEW_SERVICES_SUCCESS = 'FETCH_NEW_SERVICES_SUCCESS';
export const FETCH_NEW_SERVICES_FAILURE = 'FETCH_NEW_SERVICES_FAILURE';

export const FETCH_SERVICES_ASSIGNED_START = 'FETCH_SERVICE_ASSIGNED_START';
export const FETCH_SERVICES_ASSIGNED_SUCCESS = 'FETCH_SERVICE_ASSIGNED_SUCCESS';
export const FETCH_SERVICES_ASSIGNED_FAILURE = 'FETCH_SERVICE_ASSIGNED_FAILURE';

export const FETCH_SERVICES_DONE_START = 'FETCH_SERVICE_DONE_START';
export const FETCH_SERVICES_DONE_SUCCESS = 'FETCH_SERVICE_DONE_SUCCESS';
export const FETCH_SERVICES_DONE_FAILURE = 'FETCH_SERVICE_DONE_FAILURE';

export const SERVICE_HANDLE_START = 'SERVICE_HANDLE_START';
export const SERVICE_HANDLE_SUCCESS = 'SERVICE_HANDLE_SUCCESS';
export const SERVICE_HANDLE_FAILURE = 'SERVICE_HANDLE_FAILURE';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';

export const FETCH_INTERNAL_ORDERS_START = 'FETCH_INTERNAL_ORDERS_START';
export const FETCH_INTERNAL_ORDERS_SUCCESS = 'FETCH_INTERNAL_ORDERS_SUCCESS';
export const FETCH_INTERNAL_ORDERS_FAILURE = 'FETCH_INTERNAL_ORDERS_FAILURE';

export const FETCH_COMPLAINTS_START = 'FETCH_COMPLAINTS_START';
export const FETCH_COMPLAINTS_SUCCESS = 'FETCH_COMPLAINTS_SUCCESS';
export const FETCH_COMPLAINTS_FAILURE = 'FETCH_COMPLAINTS_FAILURE';

export const DELETE_SERVICE_START = 'DELETE_SERVICE_START';
export const DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_SUCCESS';
export const DELETE_SERVICE_FAILURE = 'DELETE_SERVICE_FAILURE';

export const SEND_ADMIN_NOTIFICATION = 'SEND_ADMIN_NOTIFICATION';
